=== RESTyard/RESTyard/Source/RESTyard.ContractFirst/RESTyard.Generator/Hypermedia.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	targetNamespace="http://schema.bluehands.de/2022/Hypermedia.xsd"
    xmlns:hm="http://schema.bluehands.de/2022/Hypermedia.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:complexType name="HypermediaType">
		<xs:sequence>
			<xs:element name="TransferParameters" type="hm:TransferParametersType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="Documents" type="hm:DocumentsType" maxOccurs="1" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<!-- Document -->
	<xs:complexType name="ClassificationsType">
		<xs:sequence>
			<xs:element name="Classification" type="hm:ClassificationType" maxOccurs="unbounded" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ClassificationType">
		<xs:attribute type="xs:string" name="class" use="required"/>
	</xs:complexType>

	<xs:complexType name="DocumentsType">
		<xs:sequence>
			<xs:element name="Document" type="hm:DocumentType" maxOccurs="unbounded" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DocumentType">
		<xs:sequence>
			<xs:element name="Classifications" type="hm:ClassificationsType" minOccurs="0" maxOccurs="1" ></xs:element>
			<xs:element name="Properties" type="hm:PropertiesType" minOccurs="0" maxOccurs="1" ></xs:element>
			<xs:element name="Entities" type="hm:EntitiesType" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="Operations" type="hm:OperationsType" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="Links" type="hm:LinksType" minOccurs="0" maxOccurs="1" ></xs:element>
			<xs:element name="Policies" type="hm:PoliciesType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute type="xs:ID" name="name" use="required"/>
		<xs:attribute type="xs:string" name="title" use="optional"/>
		<xs:attribute type="xs:boolean" name="isQueryResult" use="optional"/>
		<xs:attribute type="xs:boolean" name="hasSelfLink" default="true" use="optional" />
		<xs:attribute type="xs:IDREF" name="parentDocument" use="optional" />
	</xs:complexType>

	<!-- Properties -->

	<xs:complexType name="PropertiesType">
		<xs:sequence>
			<xs:element name="Property" type="hm:PropertyType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PropertyType">
		<xs:attribute type="xs:string" name="name" use="required"/>
		<xs:attribute type="xs:string" name="type" use="required"/>
		<xs:attribute type="xs:boolean" name="mandatory" use="optional"/>
		<xs:attribute type="xs:boolean" name="isKey" use="optional"/>
		<xs:attribute type="xs:boolean" name="hidden" use="optional"/>
	</xs:complexType>

	<!-- Entities -->

	<xs:complexType name="EntitiesType">
		<xs:sequence>
			<xs:element name="Entity" type="hm:EntityType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EntityType">
		<xs:attribute type="xs:string" name="collectionName" use="required"/>
		<xs:attribute type="xs:IDREF" name="document" use="optional"/>
		<xs:attribute type="xs:IDREF" name="referencedDocument" use="optional"/>
	</xs:complexType>

	<!-- Operations -->

	<xs:complexType name="OperationsType">
		<xs:sequence>
			<xs:element name="Operation" type="hm:OperationType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OperationType">
		<xs:sequence>
			<xs:element name="Policies" type="hm:PoliciesType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required"/>
		<xs:attribute type="hm:method" name="method" use="required"/>
		<xs:attribute type="xs:string" name="title" use="optional"/>
		<xs:attribute type="xs:IDREF" name="parameterTypeName" use="optional"/>
		<xs:attribute type="xs:IDREF" name="resultDocument" use="optional"/>
	</xs:complexType>

	<!-- Parameter -->
	<xs:complexType name="TransferParametersType">
		<xs:sequence>
			<xs:element name="Parameters" type="hm:ParameterType" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element name="ExternalParameters" type="hm:ExternalParameterType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ParameterType">
		<xs:sequence>
			<xs:element name="Property" type="hm:PropertyType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:ID" name="typeName" use="required"/>
		<xs:attribute type="xs:boolean" name="usedForQueries" use="required"/>
		<xs:attribute type="xs:boolean" name="usedForActions" use="required"/>
		<xs:attribute type="xs:IDREF" name="parentType" use="optional" />
  </xs:complexType>

	<xs:complexType name="ExternalParameterType">
		<xs:attribute type="xs:ID" name="typeName" use="required" />
  </xs:complexType>

	<xs:complexType name="QueryParametersType">
		<xs:sequence>
			<xs:element name="QueryParameter" type="hm:QueryParameterType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryParameterType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="parameterName" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- Links -->

	<xs:complexType name="LinksType">
		<xs:sequence>
			<xs:element name="Link" type="hm:LinkType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResultDocumentsType">
		<xs:sequence>
			<xs:element name="ResultDocument" type="hm:ResultDocumentType" maxOccurs="unbounded" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResultDocumentType">
		<xs:attribute type="xs:IDREF" name="document" use="required"/>
	</xs:complexType>
	<xs:complexType name="LinkType">
		<xs:sequence>
			<xs:element name="QueryParameters" type="hm:QueryParametersType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="ResultDocuments" type="hm:ResultDocumentsType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="rel" use="required"/>
		<xs:attribute type="xs:IDREF" name="document" use="optional"/>
		<xs:attribute type="xs:string" name="query" use="optional"/>
		<xs:attribute type="xs:string" name="contentType" use="optional" />
		<xs:attribute type="xs:string" name="parameterTypeName" use="optional"/>
		<xs:attribute type="xs:boolean" name="mandatory" use="required" />
	</xs:complexType>

	<!-- Others -->

	<xs:simpleType name="method">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Post"/>
			<xs:enumeration value="Delete"/>
			<xs:enumeration value="Patch"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Policies & Permissions-->

	<xs:complexType name ="PoliciesType">
		<xs:sequence>
			<xs:element name="Permissions" type="hm:PermissionsType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PermissionsType">
		<xs:sequence>
			<xs:element name="Permission" type="hm:PermissionType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute type="xs:boolean" name="authorize" use="optional" default="true"/>
	</xs:complexType>
	<xs:complexType name ="PermissionType">
		<xs:attribute type="xs:string" name="scope" use="required"/>
	</xs:complexType>

	<!-- Root -->
  <!-- Defining the proper xpath here is a bit tricky. See https://docstore.mik.ua/orelly/xml/schema/ch09_02.htm for guidance-->
  <xs:element name="Hypermedia" type="hm:HypermediaType">
    <xs:key name="PK_Document">
      <xs:selector xpath=".//hm:Document" />
      <xs:field xpath="@name" />
    </xs:key>
    <xs:key name="PK_Parameter">
      <xs:selector xpath=".//hm:Parameters|.//hm:ExternalParameters" />
      <xs:field xpath="@typeName" />
    </xs:key>

    <xs:keyref name="FK_Document_ParentDocument" refer="hm:PK_Document">
      <xs:selector xpath=".//hm:Document" />
      <xs:field xpath="@parentDocument" />
    </xs:keyref>
    <xs:keyref name="FK_Entity_Document" refer="hm:PK_Document">
      <xs:selector xpath=".//hm:Entity" />
      <xs:field xpath="@document" />
    </xs:keyref>
    <xs:keyref name="FK_Entity_ReferencedDocument" refer="hm:PK_Document">
      <xs:selector xpath=".//hm:Entity" />
      <xs:field xpath="@referencedDocument" />
    </xs:keyref>
    <xs:keyref name="FK_Operation_ParameterTypeName" refer="hm:PK_Parameter">
      <xs:selector xpath=".//hm:Operation" />
      <xs:field xpath="@parameterTypeName" />
    </xs:keyref>
    <xs:keyref name="FK_Operation_ResultDocument" refer="hm:PK_Document">
      <xs:selector xpath=".//hm:Operation" />
      <xs:field xpath="@resultDocument" />
    </xs:keyref>
    <xs:keyref name="FK_Parameter_ParentType" refer="hm:PK_Parameter">
      <xs:selector xpath=".//hm:Parameter" />
      <xs:field xpath="@parentType" />
    </xs:keyref>
    <xs:keyref name="FK_ResultDocument_Document" refer="hm:PK_Document">
      <xs:selector xpath=".//hm:ResultDocument" />
      <xs:field xpath="@document" />
    </xs:keyref>
    <xs:keyref name="FK_Link_Document" refer="hm:PK_Document">
      <xs:selector xpath=".//hm:Link" />
      <xs:field xpath="@document" />
    </xs:keyref>
  </xs:element>
</xs:schema>

=== RESTyard/RESTyard/Source/CarShack/Hypermedia/Schema.xml
<?xml version="1.0" encoding="utf-8"?>

<Hypermedia xmlns="http://schema.bluehands.de/2023/Hypermedia.xsd"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://schema.bluehands.de/2023/Hypermedia.xsd ../../RESTyard.ContractFirst/RESTyard.Generator/Hypermedia.xsd">
  <TransferParameters>
    <Parameters typeName="CreateCustomerParameters" usedForQueries="false" usedForActions="true">
      <Property name="Name" type="string" mandatory="true" />
    </Parameters>
    <Parameters typeName="BuyCarParameters" usedForQueries="false" usedForActions="true">
      <Property name="Brand" type="string" mandatory="true" />
      <Property name="CarId" type="int" mandatory="true" />
      <Property name="Price" type="double" />
      <Property name="HiddenProperty" type="double" mandatory="false" hidden="true" />
    </Parameters>
    <Parameters typeName="BuyLamborghiniParameters" parentType="BuyCarParameters" usedForActions="true"
                usedForQueries="true">
      <Property name="Color" type="string" mandatory="true" />
      <Property name="OptionalProperty" type="int" />
    </Parameters>
    <Parameters typeName="BuyLamborghinettaParameters" parentType="BuyLamborghiniParameters" usedForActions="true"
                usedForQueries="true">
      <Property name="HorsePower" type="int" mandatory="true" />
    </Parameters>
    <Parameters typeName="NewAddress" usedForQueries="false" usedForActions="true">
      <Property name="Address" type="string" mandatory="true" />
    </Parameters>
    <ExternalParameters typeName="MarkAsFavoriteParameters" usedForActions="true" usedForQueries="false" />
    <ExternalParameters typeName="CustomerQuery" />
  </TransferParameters>
  <Documents>
    <Document name="HypermediaEntrypoint" title="Entry to the Rest API">
      <Classifications>
        <Classification class="Entrypoint" />
      </Classifications>
      <Links>
        <Link rel="CustomersRoot" mandatory="true" document="HypermediaCustomersRoot" />
        <Link rel="CarsRoot" mandatory="true" document="HypermediaCarsRoot" />
      </Links>
    </Document>
    <Document name="HypermediaCarsRoot" title="The Cars API">
      <Classifications>
        <Classification class="CarsRoot" />
      </Classifications>
      <Links>
        <Link rel="NiceCar" document="DerivedCar" mandatory="true" />
        <Link rel="SuperCar" document="HypermediaCar" mandatory="true" />
      </Links>
    </Document>
    <Document name="HypermediaCar" title="A Car">
      <Classifications>
        <Classification class="Car" />
      </Classifications>
      <Properties>
        <Property name="Id" type="int" isKey="true" />
        <Property name="Brand" type="string" isKey="true" />
        <Property name="PriceDevelopment" type="IEnumerable&lt;float&gt;" />
        <Property name="PopularCountries" type="List&lt;Country&gt;" />
        <Property name="MostPopularIn" type="Country" />
      </Properties>
    </Document>
    <Document name="DerivedCar" title="Derived Car" parentDocument="HypermediaCar">
      <Classifications>
        <Classification class="DerivedCar" />
      </Classifications>
      <Properties>
        <Property name="DerivedProperty" type="string" />
      </Properties>
      <Entities>
        <Entity collectionName="item" document="HypermediaCustomer" />
      </Entities>
      <Operations>
        <Operation name="Derived" method="Post" title="Derived Operation" />
      </Operations>
      <Links>
        <Link rel="DerivedLink" mandatory="false" document="HypermediaCustomer" />
      </Links>
    </Document>
    <Document name="NextLevelDerivedCar" title="Derives from Derived Car" parentDocument="DerivedCar">
      <Classifications>
        <Classification class="NextLevelDerivedCar" />
      </Classifications>
      <Properties>
        <Property name="NextLevelDerivedProperty" type="string" />
      </Properties>
    </Document>
    <Document name="HypermediaCustomersRoot" title="The Customers API">
      <Classifications>
        <Classification class="CustomersRoot" />
      </Classifications>
      <Operations>
        <Operation name="CreateCustomer" method="Post" title="Request creation of a new Customer."
                   parameterTypeName="CreateCustomerParameters" resultDocument="HypermediaCustomer" />
        <Operation name="CreateQuery" method="Post" title="Query the Customers collection."
                   parameterTypeName="CustomerQuery" />
      </Operations>
      <Links>
        <Link rel="all" document="HypermediaCustomerQueryResult" query="CustomerQuery" mandatory="true" />
        <Link rel="BestCustomer" document="HypermediaCustomer" mandatory="true" />
        <Link rel="GreatSite" document="HypermediaCustomer" mandatory="true" />
      </Links>
    </Document>
    <Document name="HypermediaCustomer">
      <Classifications>
        <Classification class="Customer" />
      </Classifications>
      <Properties>
        <Property name="Id" type="int" hidden="true" mandatory="true" />
        <Property name="Age" type="int" />
        <Property name="FullName" type="string" />
        <Property name="Address" type="string" />
        <Property name="IsFavorite" type="bool" mandatory="true" />
      </Properties>
      <Operations>
        <Operation name="CustomerMove" method="Post" title="A Customer moved to a new location."
                   parameterTypeName="NewAddress" />
        <Operation name="CustomerRemove" method="Delete" title="Remove a Customer." />
        <Operation name="MarkAsFavorite" method="Post" title="Marks a Customer as a favorite buyer."
                   parameterTypeName="MarkAsFavoriteParameters" />
        <Operation name="BuyCar" method="Post" title="Buy a car." parameterTypeName="BuyCarParameters" />
      </Operations>
    </Document>
    <Document name="HypermediaCustomerQueryResult" title="Query result on Customer" isQueryResult="true">
      <Classifications>
        <Classification class="CustomersQueryResult" />
      </Classifications>
      <Properties>
        <Property name="TotalEntities" type="int" />
        <Property name="CurrentEntitiesCount" type="int" />
      </Properties>
      <Entities>
        <Entity collectionName="item" document="HypermediaCustomer" />
      </Entities>
    </Document>
  </Documents>
</Hypermedia>
